server:
  port: 7000

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:6379/eureka

spring:
  application:
    name: shmily-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
#        - id: admin
#            uri: lb://shmily-admin
#            predicates:
#              - Path=/admin/**
#
#        - id: user
#            uri: lb://shmily-user
#            predicates:
#              - Path=/user/**
